<a href="https://colab.research.google.com/github/atul812/Amazon_ML_Challenge_2026/blob/main/01_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')

# Change directory to your shared folder path
# (Adjust this path depending on where you placed it in your Drive)
os.chdir('/content/drive/My Drive/Amazon_ML_Challenge_2026')

# Verify the path by listing the contents
print(os.listdir('.'))

Mounted at /content/drive
['dataset', 'output', 'utils', 'notebook']

In [ ]:
import pandas as pd

# Test loading Source 1 with explicit tab separator
df_train_s1 = pd.read_csv('dataset/train/train_source1.tsv', sep='\t')

# Print columns and first 2 rows to verify
print("Columns:", df_train_s1.columns.tolist())
display(df_train_s1.head(2))

Columns: ['entity_id', 'business_name', 'business_address', 'country']

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US

In [ ]:
import pandas as pd
import re
import os

# Define a function to do all the cleaning steps at once
def clean_dataframe(df):
    # Step 2: Replace missing values with empty strings
    df = df.fillna('')

    # Apply cleaning to the three text columns
    cols_to_clean = ['business_name', 'business_address', 'country']

    for col in cols_to_clean:
        if col in df.columns:
            # Step 3: Convert to string and lowercase
            df[col] = df[col].astype(str).str.lower()

            # Step 4: Replace all punctuation (anything that is not a letter, number, or space) with a space
            df[col] = df[col].str.replace(r'[^\w\s]', ' ', regex=True)

            # Step 5: Replace multiple spaces with a single space, and strip edges
            df[col] = df[col].str.replace(r'\s+', ' ', regex=True).str.strip()

    return df

# Step 1: Load the training data (Make sure your Google Drive is mounted first!)
print("Loading data...")
train_s1 = pd.read_csv('dataset/train/train_source1.tsv', sep='\t')
train_s2 = pd.read_csv('dataset/train/train_source2.tsv', sep='\t')
train_s3 = pd.read_csv('dataset/train/train_source3.tsv', sep='\t')

print("Cleaning data...")
# Run the cleaning function on all datasets
clean_s1 = clean_dataframe(train_s1)
clean_s2 = clean_dataframe(train_s2)
clean_s3 = clean_dataframe(train_s3)

# Display a sample to verify it worked
print("\nSample of cleaned Source 1:")
display(clean_s1.head(3))

# Step 6: Save the cleaned versions back to Drive for the next team member
print("Saving cleaned data for Member 2...")
# We save them as TSV to maintain consistency
clean_s1.to_csv('dataset/train/clean_train_source1.tsv', sep='\t', index=False)
clean_s2.to_csv('dataset/train/clean_train_source2.tsv', sep='\t', index=False)
clean_s3.to_csv('dataset/train/clean_train_source3.tsv', sep='\t', index=False)
print("Done!")

Loading data...
Cleaning data...

Sample of cleaned Source 1:

,entity_id,business_name,business_address,country
0,S1-925783039,orelee s barbershop,1795 westchester drive high point nc,us
1,S1-773889195,prime money,17560 ellis road tahlequah ok,us
2,S1-377745466,b retail inc,1712 montebello avenue phoenix az,us

Saving cleaned data for Member 2...
Done!